sudo: false
language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  # - 2.6  # These versions are disabled due to failures on Travis' side.
  # - pypy
  # - pypy3
env:
  matrix:
    - $COVPYYAML=cov3-default,coveralls3
    - $COVPYYAML=cov4-pyyaml,coveralls4
    - $COVPYYAML=cov41-pyyaml,coveralls41
    - $COVPYYAML=cov3-default,coveralls3
    - $COVPYYAML=cov4-pyyaml,coveralls4
    - $COVPYYAML=cov41-pyyaml,coveralls41
install:
  - pip install tox
script:
  - tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d . | sed -e 's/pypypy/pypy/')-$COVPYYAML
